[project]
name = "duckdb-medium"
version = "0.1.0"
description = "Prep for DuckDB Medium Post"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "faker>=29.0.0",
    "jupyter>=1.1.1",
    "rstr>=3.2.2",
]
