version: 3

vars:
  CONTAINER_NAME: local-postgres

tasks:
  build-postgres-image:
    desc: Build the PostgreSQL image 
    cmds:
      - docker build --tag {{.CONTAINER_NAME}} - < Dockerfile 
  
  build-postgres-image-no-cache:
    desc: Build the PostgreSQL image without cache
    cmds:
      - docker build --no-cache --tag {{.CONTAINER_NAME}} - < Dockerfile 

  run-postgres:
    desc: Run the `postgres` container
    dotenv: ['.env']
    status:
      - '[ "$(docker ps -f name={{.CONTAINER_NAME}}_container --filter status=running -q)" != "" ]'
    cmds:
      - |
        docker run -d -p 5432:5432 -v ./psql_data:/var/lib/psql/data \
        --name {{.CONTAINER_NAME}}_container \
        -e  POSTGRES_USER=$PGUSER \
        -e  POSTGRES_PASSWORD=$PGPASSWORD \
        -e  POSTGRES_DB=$PGDATABASE \
        -t {{.CONTAINER_NAME}}

  stop-postgres:
    desc: Stop the `postgres` container
    cmds:
      - docker stop {{.CONTAINER_ID}}
      - docker rm {{.CONTAINER_NAME}}_container
    vars:
      CONTAINER_ID:
        sh: docker ps -f name={{.CONTAINER_NAME}}_container --filter status=running -q

  run-psql:
    desc: run psql
    deps: [run-postgres]
    cmds:
      - sleep 5s
      - ./psql.sh
